/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Aleksa
 */
public class InputFieldPanel extends javax.swing.JPanel implements IGetValue{

    /**
     * Creates new form InputFieldPanel
     */
    public InputFieldPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabValue = new javax.swing.JLabel();
        jLabError = new javax.swing.JLabel();
        jtxt = new javax.swing.JTextField();

        jLabValue.setText("jLabel1");

        jLabError.setText("jLabel1");

        jtxt.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabError, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabValue, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabValue)
                    .addComponent(jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * vraca prazan string ako je los unos,tj ako ima brojeva,cisto za primer
     * @return 
     */
    @Override
    public Object getValue() {
        
        Pattern pattern = Pattern.compile("[0-9]");
        Matcher matcher = pattern.matcher(jtxt.getText());
        
        if (matcher.find()) {
            jLabError.setText("Uneli ste brojeve");
            jtxt.setText("");
            
            return "";
        }
        
        String output = jtxt.getText();
        jtxt.setText("");
        jLabError.setText("");
        return output;
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabError;
    private javax.swing.JLabel jLabValue;
    private javax.swing.JTextField jtxt;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getjLabError() {
        return jLabError;
    }

    public javax.swing.JLabel getjLabValue() {
        return jLabValue;
    }

    public javax.swing.JTextField getJtxt() {
        return jtxt;
    }

    
    
}
